# Generated by Django 5.2.7 on 2025-10-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('finished', 'Finished'), ('paused', 'Paused')], default='draft', max_length=20),
        ),
    ]
