# Generated by Django 5.2.7 on 2025-10-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_bounces_campaign_clicks_campaign_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='from_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='messenger',
            field=models.CharField(choices=[('email', 'Email')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
