# Generated by Django 5.2.7 on 2025-10-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bcc_recipients',
            field=models.TextField(blank=True, help_text='Comma-separated list of email addresses', verbose_name='BCC Recipients'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cc_recipients',
            field=models.TextField(blank=True, help_text='Comma-separated list of email addresses', verbose_name='CC Recipients'),
        ),
    ]
