# Generated by Django 5.2.7 on 2025-10-23 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_from_address_campaign_messenger_and_more'),
        ('subscribers', '0003_auto_20251023_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='segments',
        ),
        migrations.AddField(
            model_name='campaign',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='subscribers.segment'),
        ),
    ]
