# Generated by Django 5.2.7 on 2025-10-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_campaign_segments_campaign_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='from_address',
            new_name='from_email',
        ),
        migrations.AddField(
            model_name='campaign',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='subscribers.segment'),
        ),
    ]
