# Generated by Django 5.2.7 on 2025-10-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20251023_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='list',
        ),
    ]
