# Generated by Django 5.2.7 on 2025-10-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_remove_campaign_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
