# Generated by Django 5.2.7 on 2025-10-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpprovider',
            name='bounce_rate_threshold',
            field=models.FloatField(default=5.0, help_text='The bounce rate at which to deactivate the provider.', verbose_name='Bounce Rate Threshold (%)'),
        ),
    ]
