# Generated by Django 5.2.7 on 2025-10-23 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_alter_subscriber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segment',
            name='opt_in_type',
            field=models.CharField(choices=[('single', 'Single opt-in'), ('double', 'Double opt-in')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='segment',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='segment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
