# Generated by Django 5.2.7 on 2025-10-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20251023_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='opt_in_type',
            new_name='optin',
        ),
        migrations.AddField(
            model_name='segment',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('temporary', 'Temporary')], default='private', max_length=10),
        ),
    ]
