# Generated by Django 5.2.7 on 2025-10-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_smtpprovider_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='from_email',
            field=models.EmailField(max_length=254, verbose_name='From Email'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='from_name',
            field=models.CharField(max_length=255, verbose_name='From Name'),
        ),
    ]
