# Generated by Django 5.2.7 on 2025-10-27 08:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_from_email_alter_campaign_from_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='html_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='<p>Default campaign content</p>', verbose_name='HTML Content'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='HTML Content'),
        ),
    ]
