# Generated by Django 5.2.7 on 2025-10-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_bcc_recipients_campaign_cc_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Attachment'),
        ),
    ]
