# Generated by Django 5.2.7 on 2025-10-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_smtpprovider_bounce_rate_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpprovider',
            name='is_warming_up',
            field=models.BooleanField(default=False, verbose_name='Warming Up'),
        ),
        migrations.AddField(
            model_name='smtpprovider',
            name='warmup_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schedule for warm-up, e.g., {"1": 50, "2": 100, "14": 10000}', verbose_name='Warm-up Schedule'),
        ),
        migrations.AddField(
            model_name='smtpprovider',
            name='warmup_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Warm-up Start Time'),
        ),
    ]
